[settings]
experimental = true
jobs = 12
plugin_autoupdate_last_check_duration = "1 week"
idiomatic_version_file_enable_tools = []
python.uv_venv_auto = true

[tools]
usage = "latest"
task = "latest"
node = "lts"
terraform = "latest"
opentofu = "latest"
rust = "latest"
helmfile = "latest"
helm = "latest"
jq = "latest"
yq = "latest"
gcloud = "latest"
awscli = "latest"
snyk = "latest"
cloudflared = "latest"
go = "sub-0.1:latest"
bun = "latest"
vault = "latest"
uv = "latest"
glow = "latest"
tmux = "latest"
mc = "latest"
dasel = "latest"
neovim = "latest"
kubectl = "1.32"
doppler = "latest"
gh = "latest"
poetry = "latest"
hyperfine = "latest"
redis-cli = "7"
k9s = "latest"
terragrunt = "latest"
tflint = "latest"
delta = "latest"
atlas = "latest"
trivy = "latest"
duckdb = "latest"
act = "latest"
bitwarden = "latest"
eza = "latest"
xh = "latest"
dust = "latest"
dua = "latest"
yazi = "latest"
mask = "latest"
mprocs = "latest"
postgres = "latest"
python = "sub-0.1:latest"
dotnet-core = "9"
aqua = "latest"
tokei = "latest"
gitleaks = "latest"
krew = "latest"
