[settings]
experimental = true
plugin_autoupdate_last_check_duration = "1 week"
idiomatic_version_file_enable_tools = []
python.uv_venv_auto = false

[tools]
usage = "latest"
task = "latest"
node = "lts"
terraform = "latest"
opentofu = "latest"
rust = "latest"
helmfile = "latest"
helm = "latest"
jq = "latest"
yq = "latest"
gcloud = "latest"
awscli = "latest"
snyk = "latest"
cloudflared = "latest"
go = "sub-0.0.1:latest"
bun = "latest"
vault = "latest"
uv = "latest"
glow = "latest"
tmux = "latest"
dasel = "latest"
neovim = "latest"
kubectl = "1.32"
doppler = "latest"
poetry = "latest"
hyperfine = "latest"
redis-cli = "7"
k9s = "latest"
terragrunt = "latest"
tflint = "latest"
delta = "latest"
atlas = "latest"
trivy = "latest"
duckdb = "latest"
act = "latest"
bitwarden = "latest"
eza = "latest"
xh = "latest"
dust = "latest"
dua = "latest"
yazi = "latest"
mask = "latest"
mprocs = "latest"
postgres = "latest"
python = "sub-0.1:latest"
dotnet-core = "9"
aqua = "latest"
tokei = "latest"
gitleaks = "latest"
krew = "latest"
java = "latest"
imagemagick = "latest"
infracost = "latest"
gemini-cli = "latest"
gh = "latest"
dvc = "latest"
claude-code = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-x64/claude"

[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
opencode = "latest"
